fix

diff --git a/tasks_build_img_cmk.yaml b/tasks_build_img_cmk.yaml
--- a/tasks_build_img_cmk.yaml
+++ b/tasks_build_img_cmk.yaml
@@ -196,38 +196,38 @@ tasks:
         - IMAGE_SIGNING_ENABLED
         - OCM_SIGNING_ENABLED
     cmd: |
-        set -euo pipefail
+      set -euo pipefail
+    
+      TAG=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/repos/{{.ORG_NAME}}/{{.CMK_CORE_IMAGE_NAME}}/tags" | jq -r '.[].name' | sort -V | tail -n1)
+    
+      if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
+        echo "❌ No tags found. Looking into `repos/{{.ORG_NAME}}/{{.CMK_CORE_IMAGE_NAME}}/tags`"
+        exit 1
+      fi
       
-        TAG=$(curl -s -H "Accept: application/vnd.github+json" "https://api.github.com/repos/{{.ORG_NAME}}/{{.CMK_CORE_IMAGE_NAME}}/tags" | jq -r '.[].name' | sort -V | tail -n1)
+      docker manifest push {{.BASE_IMAGE}}:$TAG
+
+#     task build:img:sign VERSION="${TAG}" BASE_IMAGE="{{.BASE_IMAGE}}" CRANE_PLATFORM=""
+
+      # Signing the image
+      if [ "{{.IMAGE_SIGNING_ENABLED}}" != "true" ]; then
+        echo "⚠️ Image signing is disabled (IMAGE_SIGNING_ENABLED is not 'true'). Skipping."
+        exit 0
+      fi
       
-        if [ -z "$TAG" ] || [ "$TAG" = "null" ]; then
-          echo "❌ No tags found. Looking into `repos/{{.ORG_NAME}}/{{.CMK_CORE_IMAGE_NAME}}/tags`"
-          exit 1
-        fi
-        
-        docker manifest push {{.BASE_IMAGE}}:$TAG
-
-  #     task build:img:sign VERSION="${TAG}" BASE_IMAGE="{{.BASE_IMAGE}}" CRANE_PLATFORM=""
-
-        # Signing the image
-        if [ "{{.IMAGE_SIGNING_ENABLED}}" != "true" ]; then
-          echo "⚠️ Image signing is disabled (IMAGE_SIGNING_ENABLED is not 'true'). Skipping."
-          exit 0
-        fi
-        
-        set -eu
-        
-        if [ -z "$COSIGN_PRIVATE_KEY" ] || [ -z "$COSIGN_PASSWORD" ]; then
-          echo "❌ Error: Missing COSIGN_PRIVATE_KEY or COSIGN_PASSWORD." >&2
-          exit 1
-        fi
-        
-        trap 'rm -f "{{.ROOT_DIR2}}/cosign.key"' EXIT
-        echo "$COSIGN_PRIVATE_KEY" > "{{.ROOT_DIR2}}/cosign.key"
-        
-        DIGEST=$({{.CRANE}} digest {{.BASE_IMAGE}}:$TAG)
-        {{.COSIGN}} sign --yes --key "{{.ROOT_DIR2}}/cosign.key" "{{.BASE_IMAGE}}@$DIGEST"
-        echo "✅ Successfully signed image: {{.BASE_IMAGE}}@$DIGEST"
+      set -eu
+      
+      if [ -z "$COSIGN_PRIVATE_KEY" ] || [ -z "$COSIGN_PASSWORD" ]; then
+        echo "❌ Error: Missing COSIGN_PRIVATE_KEY or COSIGN_PASSWORD." >&2
+        exit 1
+      fi
+      
+      trap 'rm -f "{{.ROOT_DIR2}}/cosign.key"' EXIT
+      echo "$COSIGN_PRIVATE_KEY" > "{{.ROOT_DIR2}}/cosign.key"
+      
+      DIGEST=$({{.CRANE}} digest {{.BASE_IMAGE}}:$TAG)
+      {{.COSIGN}} sign --yes --key "{{.ROOT_DIR2}}/cosign.key" "{{.BASE_IMAGE}}@$DIGEST"
+      echo "✅ Successfully signed image: {{.BASE_IMAGE}}@$DIGEST"
 
     internal: true
 
