fix

diff --git a/tasks_build_img_cmk.yaml b/tasks_build_img_cmk.yaml
--- a/tasks_build_img_cmk.yaml
+++ b/tasks_build_img_cmk.yaml
@@ -154,9 +154,15 @@ tasks:
 
 
         BUILD_ARGS=()
+  
         for image in $WATCHED_IMAGES; do
           VAR_NAME=$(echo "$image" | tr '[:lower:]-' '[:upper:]_')
-          BUILD_ARGS+=(--build-arg "${VAR_NAME}_IMAGE=${TAGS[$image]}-{{.OS}}-{{.ARCH}}")
+          TAG_VALUE=${TAGS[$image]}
+          if [ -z "$TAG_VALUE" ]; then
+            echo "❌ Tag missing for image: $image"
+            exit 1
+          fi
+          BUILD_ARGS+=(--build-arg "${VAR_NAME}_IMAGE=${TAG_VALUE}-{{.OS}}-{{.ARCH}}")
         done
 
         IMAGE="{{.BASE_IMAGE}}:$MAIN_TAG-{{.OS}}-{{.ARCH}}"
