fix: add task for the plugins to incorporate many binaries in one image

diff --git a/tasks_build_img.yaml b/tasks_build_img.yaml
--- a/tasks_build_img.yaml
+++ b/tasks_build_img.yaml
@@ -191,10 +191,6 @@ tasks:
       vars:
       - IMG
       - BASE_IMG
-    deps:
-      - tools:crane
-      - tools:cosign
-      - tools:localtmp
     vars:
       IMAGE_SIGNING_ENABLED: '{{ env "IMAGE_SIGNING_ENABLED" | default "false" }}'
     cmds:
@@ -205,25 +201,90 @@ tasks:
       cmd: 'docker manifest create {{.IMG}} --amend {{.IMG}}-{{.ITEM.OS}}-{{.ITEM.ARCH}}'
     - 'echo "Pushing image {{.IMG}}"'
     - 'docker manifest push {{.IMG}}'
-    - |
-      set -eu
-      if [ "${IMAGE_SIGNING_ENABLED:-false}" != "true" ]; then
-        echo "⚠️ Image signing is disabled (IMAGE_SIGNING_ENABLED is not 'true'). Skipping." >&2
-        exit 0
-      fi
-      
-      if [ -z "$COSIGN_PRIVATE_KEY" ] || [ -z "$COSIGN_PASSWORD" ]; then
-        echo "❌ Error: Missing COSIGN_PRIVATE_KEY or COSIGN_PASSWORD." >&2
-        exit 1
-      fi
-      
-      trap 'rm -f "{{.ROOT_DIR2}}/cosign.key"' EXIT
-      echo "$COSIGN_PRIVATE_KEY" > "{{.ROOT_DIR2}}/cosign.key"
-  
-      DIGEST=$({{.CRANE}} digest {{.IMG}})
-      {{.COSIGN}} sign --yes --key "{{.ROOT_DIR2}}/cosign.key" "{{.BASE_IMG}}@$DIGEST"
-      echo "✅ Successfully signed multi-arch image: {{.BASE_IMG}}@$DIGEST"
+    - task: sign
+      vars:
+        IMG: '{{.IMG}}'
+        BASE_IMG: '{{.BASE_IMG}}'
     internal: true
+
+  push-one:
+    desc: "  Push one the multi-platform image."
+    requires:
+      vars:
+        - IMAGE_NAME
+        - VERSION
+    deps:
+      - build:bin:all
+    vars:
+      IMAGE_BASE:
+        sh: 'PROJECT_ROOT="{{.ROOT_DIR2}}" {{.TASKFILE_DIR2}}/get-registry.sh --image'
+    cmds:
+      - task: prepare-docker-builder
+      - for:
+          matrix:
+            OS: [ "linux" ] # distroless base image only supports linux
+        vars:
+          OS: '{{.ITEM.OS}}'
+          IMAGE_NAME: '{{.IMAGE_NAME}}'
+          VERSION: '{{.VERSION}}'
+          IMAGE_BASE: '{{.IMAGE_BASE}}'
+        task: build-one-internal
+      - task: sign
+        vars:
+          IMG: '{{.IMAGE_BASE}}/{{.IMAGE_NAME}}:{{.VERSION}}'
+          BASE_IMG: '{{.IMAGE_BASE}}/{{.IMAGE_NAME}}'
+
+  build-one-internal:
+    desc: "  Build a single image including all binaries. Requires the docker builder to have been prepared before."
+    requires:
+      vars:
+        - IMAGE_NAME
+        - VERSION
+        - OS
+        - IMAGE_BASE
+        - DOCKER_BUILDER_NAME
+    cmds:
+      - 'echo "Building image {{.IMAGE_NAME}}:{{.VERSION}}-{{.OS}}"'
+      - '[[ "{{.OS}}" == "linux" ]] || { echo "The distroless base image does only support linux as operating system."; exit 1; }'
+      - 'cat "{{.TASKFILE_DIR2}}/Dockerfile" > "{{.ROOT_DIR2}}/Dockerfile.tmp"'
+      - '( cd "{{.ROOT_DIR2}}"; docker buildx build --builder {{.DOCKER_BUILDER_NAME}} --load --platform {{.OS}} -t {{.IMAGE_BASE}}/{{.IMAGE_NAME}}:{{.VERSION}}-{{.OS}} -f Dockerfile.tmp . )'
+      - 'docker push {{.IMAGE_BASE}}/{{.IMAGE_NAME}}:{{.VERSION}}-{{.OS}}'
+      - 'rm -f "{{.ROOT_DIR2}}/Dockerfile.tmp"'
+    internal: true
+
+  sign:
+    desc: "  Sign image."
+    requires:
+      vars:
+        - IMG
+        - BASE_IMG
+    deps:
+      - tools:crane
+      - tools:cosign
+      - tools:localtmp
+    vars:
+      IMAGE_SIGNING_ENABLED: '{{ env "IMAGE_SIGNING_ENABLED" | default "false" }}'
+    cmds:
+      - |
+        set -eu
+        if [ "${IMAGE_SIGNING_ENABLED:-false}" != "true" ]; then
+          echo "⚠️ Image signing is disabled (IMAGE_SIGNING_ENABLED is not 'true'). Skipping." >&2
+          exit 0
+        fi
+        
+        if [ -z "$COSIGN_PRIVATE_KEY" ] || [ -z "$COSIGN_PASSWORD" ]; then
+          echo "❌ Error: Missing COSIGN_PRIVATE_KEY or COSIGN_PASSWORD." >&2
+          exit 1
+        fi
+        
+        trap 'rm -f "{{.ROOT_DIR2}}/cosign.key"' EXIT
+        echo "$COSIGN_PRIVATE_KEY" > "{{.ROOT_DIR2}}/cosign.key"
+        
+        DIGEST=$({{.CRANE}} digest {{.IMG}})
+        {{.COSIGN}} sign --yes --key "{{.ROOT_DIR2}}/cosign.key" "{{.BASE_IMG}}@$DIGEST"
+        echo "✅ Successfully signed multi-arch image: {{.BASE_IMG}}@$DIGEST"
+    internal: true
+
 
   tag:
     desc: "  Adds an additional tag to the multi-platform image. Image must have been built and pushed before."
