fix: binaries built to be skipped if already present

diff --git a/tasks_build_bin.yaml b/tasks_build_bin.yaml
--- a/tasks_build_bin.yaml
+++ b/tasks_build_bin.yaml
@@ -53,7 +53,20 @@ tasks:
     - for:
         var: COMPONENTS
         as: COMPONENT
-      cmd: 'CGO_ENABLED=0 GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.BUILD_TAGS}} -a -o {{.ROOT_DIR2}}/bin/{{(regexReplaceAll "\\/" .COMPONENT "-") | lower}}.{{.OS}}-{{.ARCH}} -ldflags "{{.BUILD_LDFLAGS}}" {{.ROOT_DIR2}}/cmd/{{.COMPONENT}}/'
+      cmd: |
+        set -e
+        
+        FILE_PATH="{{.ROOT_DIR2}}/bin/{{(regexReplaceAll "\\/" .COMPONENT "-") | lower}}.{{.OS}}-{{.ARCH}}"
+        SRC_DIR="{{.ROOT_DIR2}}/cmd/{{.COMPONENT}}"
+        
+        if [ -f "${FILE_PATH}" ]; then
+          echo "✅ Binary ${FILE_PATH} already built!"
+        elif [ ! -d "${SRC_DIR}" ]; then
+          echo "❌ Error: Source directory does not exist for component: ${SRC_DIR}"
+          exit 1
+        else
+          CGO_ENABLED=0 GOOS={{.OS}} GOARCH={{.ARCH}} go build {{.BUILD_TAGS}} -a -o "$FILE_PATH" -ldflags "{{.BUILD_LDFLAGS}}" "${SRC_DIR}/"
+        fi
 
   build-multi-raw:
     desc: "  Build multi-platform binaries. Skips code generation/validation tasks."
